/**
 * JAVASCRIPT FUNCTIONS:
 * 
 * FUNCTIONS ARE CODE BLOCKS THAT DO SPECIFIC "THINGS", OR TASKS. 
 * 
 * FUNCTIONS ARE LIKE RECIPES. YOU WRITE OUT THE STEPS ONCE, AND THEN YOU ARE ABLE TO CREATE THE DISH LATER ON.
 * IN JAVASCRIPT, YOU WRITE OUT THE FUNCTION ONCE AND THEN USE IT WHENEVER YOU NEED THAT TASK TO BE DONE. 
 * 
 * 1. DEFINING A FUNCTION
 *      THIS IS LIKE WRITING OUT THE STEPS OF YOUR RECIPE. YOU'RE CODING THE SPECIFIC TASKS THAT NEED TO BE ENTERED TO COMPLETE A TASK. 
 * 
 * 2. CALLING A FUNCTION
 *      THIS IS WHEN YOU ACTUALLY TELL JAVASCRIPT "HEY, REMEMBER THAT RECIPE WE MADE EARLIER? NOW MAKE THE DISH". 
 *      IN OTHER WORDS, THIS IS WHEN YOU "INVOKE" THE FUNCTION OR TELL JAVASCRIPT TO EXECUTE THE CODE BLOCK TO ACCOMPLISH THE SPECIFIC TASK. 
 * 
 * 3. PARAMETERS AND ARGUMENTS
 *      THESE ARE PARTS OF THE RECIPE THAT YOU CAN SUB OUT WITH OTHER INGREDIENTS.
 *      WITH JAVASCRIPT FUNCTIONS YOU CAN PASS IN DIFFERENT VALUES (ARGUMENTS) TO GET DIFFERENT RESULTS. 
 */

// DEFINING A FUNCTION

function sayHello(name) {
    return 'Hello, ' + name;
}

// CALLING A FUNCTION

sayHello('Colton');
let helloAlex = sayHello('Alex');
console.log(helloAlex); // Logs 'Hello, Alex' 

// PARAMETERS AND ARGUMENTS

function add(num1, num2) {
    return num1 + num2;
}

add(1, 1);
let sum = add(2, 2);
console.log(sum);

// YOU CAN NAME PARAMETERS WHATEVER YOU WOULD LIKE

function subtract(a, b) {
    return a - b;
}

console.log(subtract(10, 5));
